USE `essentialmode`;

-- INSERT INTO `items` (name, label, `limit`) VALUES
-- 	('gazbottle', 'bouteille de gaz', 11),
-- 	('fixtool', 'outils réparation', 6),
-- 	('carotool', 'outils carosserie', 4),
-- 	('blowpipe', 'Chalumeaux', 10),
-- 	('fixkit', 'Kit réparation', 5),
-- 	('carokit', 'Kit carosserie', 3)
-- ;

INSERT INTO `addon_account` (`name`, `label`, `shared`) VALUES('society_mechanic-bennys', 'Механики Benny\'s', 1);
INSERT INTO `addon_inventory` (`name`, `label`, `shared`) VALUES ('society_mechanic-bennys', 'Механики Benny\'s', 1);
INSERT INTO `jobs` (`name`, `label`, `whitelisted`) VALUES ('mechanic-bennys', 'Механик Benny\'s', 0);

INSERT INTO `job_grades` (`id`, `job_name`, `grade`, `name`, `label`, `salary`, `skin_male`, `skin_female`) VALUES
(58, 'mechanic-bennys', 0, 'recrue', 'Новичок', 60, '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 0,\r\n	\"glasses_1\" : 0,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 39,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 27,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 66,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}', '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 5,\r\n	\"glasses_1\" : 5,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 38,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 26,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 59,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}'),
(59, 'mechanic-bennys', 1, 'novice', 'Механик', 75, '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 0,\r\n	\"glasses_1\" : 0,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 39,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 27,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 66,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}', '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 5,\r\n	\"glasses_1\" : 5,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 38,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 26,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 59,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}'),
(60, 'mechanic-bennys', 2, 'experimente', 'Опытный', 85, '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 0,\r\n	\"glasses_1\" : 0,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 39,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 27,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 66,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}', '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 5,\r\n	\"glasses_1\" : 5,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 38,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 26,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 59,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}'),
(61, 'mechanic-bennys', 3, 'chief', 'Заместитель', 95, '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 0,\r\n	\"glasses_1\" : 0,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 39,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 27,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 66,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}', '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 5,\r\n	\"glasses_1\" : 5,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 38,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 26,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 59,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}'),
(62, 'mechanic-bennys', 4, 'boss', 'Босс', 120, '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 0,\r\n	\"glasses_1\" : 0,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 39,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 27,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 66,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}', '{\r\n	\"arms\" : 0,\r\n	\"bags_1\" : 0,\r\n	\"bags_2\" : 0,\r\n	\"bproof_1\" : 0,\r\n	\"bproof_2\" : 0,\r\n	\"chain_1\" : 0,\r\n	\"chain_2\" : 0,\r\n	\"decals_1\" : 0,\r\n	\"decals_2\" : 0,\r\n	\"glasses\" : 5,\r\n	\"glasses_1\" : 5,\r\n	\"helmet_1\" : -1,\r\n	\"helmet_2\" : 0,\r\n	\"mask_1\" : 0,\r\n	\"mask_2\" : 0,\r\n	\"pants_1\" : 38,\r\n	\"pants_2\" : 2,\r\n	\"shoes_1\" : 26,\r\n	\"shoes_2\" : 0,\r\n	\"torso_1\" : 59,\r\n	\"torso_2\" : 2,\r\n	\"tshirt_1\" : 15,\r\n	\"tshirt_2\" : 0\r\n}');
