Config = {}

Config.Animations = {
	["facials"] = {
		hotkey = 'M',
		label = 'Настроение',
		items = {
			["facial_normal"]   = {hotkey="A", label = "Обычное", type = "facial", data = {anim = "mood_normal_1"}, incar=1},
			["facial_happy"]    = {hotkey="B", label = "Счастливое", type = "facial", data = {anim = "mood_happy_1"}, incar=1},
			["facial_angry"]    = {hotkey="C", label = "Злое", type = "facial", data = {anim = "mood_angry_1"}, incar=1},
			["facial_sleeping"] = {hotkey="D", label = "Сонное", type = "facial", data = {anim = "mood_sleeping_1"}, incar=1},
			["facial_knockout"] = {hotkey="E", label = "Бесознательное", type = "facial", data = {anim = "mood_knockout_1"}, incar=1},
			["facial_aiming"]   = {hotkey="F", label = "Подозрительное", type = "facial", data = {anim = "mood_aiming_1"}, incar=1},
			["facial_injured"]  = {hotkey="G", label = "Удивленное", type = "facial", data = {anim = "mood_injured_1"}, incar=1},
			["facial_stressed"] = {hotkey="H", label = "Шокированное", type = "facial", data = {anim = "mood_stressed_1"}, incar=1},
			["facial_smug"]     = {hotkey="I", label = "Самодовольное", type = "facial", data = {anim = "mood_smug_1"}, incar=1},
			["facial_sulk"]     = {hotkey="J", label = "Грустное", type = "facial", data = {anim = "mood_sulk_1"}, incar=1},
			["facial_drunk"]    = {hotkey="K", label = "Пьяное", type = "facial", data = {anim = "mood_drunk_1"}, incar=1},
		}
	},
	["actions"] = {
		hotkey = 'A',
		label = 'Действия',
		items = {
			["do_smoke1"] = {hotkey="A", label = "Курить", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING", flag = 9}},
			["do_smoke2"] = {hotkey="B", label = "Курить на ходу 1", type = "dpemotes", data = {anim = "smoke2"}, incar=1},
			["do_smoke3"] = {hotkey="C", label = "Курить на ходу 2", type = "dpemotes", data = {anim = "smoke3"}, incar=1},
			["do_smoke4"] = {hotkey="D", label = "Курить на ходу Ж", type = "dpemotes", data = {anim = "smoke4"}, incar=1},
			["do_cigar2"] = {hotkey="E", label = "Сиграрета в зубах", type = "dpemotes", data = {anim = "cigar2"}, incar=1},
			["do_cigar"]  = {hotkey="F", label = "Cигара в зубах", type = "dpemotes", data = {anim = "cigar"}, incar=1},
			["do_muse"]   = {hotkey="G", label = "Музицировать", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN", flag = 9}},
			["do_sax"]    = {hotkey="H", label = "Играть на саксофоне", type = "dpemotes", data = {anim = "sax"}, incar=1},
			["do_dj"]     = {hotkey="I", label = "Диджей", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj", flag = 9}},
			["do_airguitar"] = {hotkey="J", label = "Воображаемая гитара", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar"}},
			["do_shagging"]  = {hotkey="K", label = "Сотрясать воздух", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging"}},
			["do_rock"]      = {hotkey="L", label = "Rock'n'roll", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock", upper=true, control=true, flag = 9}, incar=1},
			["do_smokepot"]  = {hotkey="M", label = "Курить косяк", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING_POT"}},
			["do_holdup"]    = {hotkey="N", label = "Схватить", type = "anim", data = {lib = "anim@am_hold_up@male", anim = "shoplift_high", upper=false, control=true, flag = 9}},
			["do_knock"]     = {hotkey="O", label = "Стучать", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@ds@base", anim = "idle_a_fp", flag = 9}, incar=1},
			["do_reachdown"] = {hotkey="P", label = "Копаться в", type = "scenario", data = {anim = "PROP_HUMAN_BUM_BIN"}},
			["do_reachup"]   = {hotkey="Q", label = "Достать сверху", type = "anim", data = {lib = "mph_hum_fin_ext-0", anim = "s_m_m_highsec_01_dual-0", upper=true, flag = 9}, incar=1},
			["do_forsake"]   = {hotkey="R", label = "Я пожалуй пойду", type = "anim", data = {lib = "abigail_mcs_2-5", anim = "csb_abigail_dual-5"}},
			["do_busted"]    = {hotkey="S", label = "Руки за голову", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_c", repeat_anim=true}},
			["do_throwup"]   = {hotkey="T", label = "Вырвать", type = "anim", data = {lib = "anim@amb@clubhouse@respawn@female@", anim = "respawn_d"}},
			["do_selfie"]    = {hotkey="U", label = "Селфи", type = "scenario", data = {anim = "world_human_tourist_mobile", upper=true, control=true}},
			["do_inspectcar"] = {hotkey="V", label = "Осмотреть Ж", type = "anim", data = {lib = "oddjobs@taxi@gyn@", anim = "idle_b_ped", flag = 9}},
			["do_roam"] = {hotkey="W", label = "Ходить задумчиво", type = "anim", data = {lib = "martin_1_int-5", anim = "cs_patricia_dual-5", flag = 9}},
			["do_shakeoff"] = {hotkey="X", label = "Отряхиваться", type = "anim", data = {lib = "move_m@_idles@shake_off", anim = "shakeoff_1", flag = 9}},
			["do_papers"] = {hotkey="Y", label = "Перебирать бумаги", type = "anim", data = {lib = "iaa_int-14", anim = "cs_lestercrest_2_dual-14", flag = 9}},
			["do_bbq"] = {hotkey="Z", label = "Барбекю", type = "scenario", data = {anim = "PROP_HUMAN_BBQ"}},
			["do_janitor"] = {hotkey="1", label = "Уборщик", type = "scenario", data = {anim = "WORLD_HUMAN_JANITOR"}},
			["do_bong"] = {hotkey="2", label = "Затянуться из бонга", type = "dpemotes", data = {anim = "bong"}, incar=1},
			["do_book"] = {hotkey="3", label = "Читать книгу", type = "dpemotes", data = {anim = "book"}, incar=1},
			["do_rose"] = {hotkey="4", label = "Достать розу", type = "dpemotes", data = {anim = "rose"}, incar=1},
			["do_box"] = {hotkey="5", label = "Достать ящик", type = "dpemotes", data = {anim = "box"}, incar=1},
			["do_makeitrain"] = {hotkey="6", label = "Бросаться деньгами", type = "dpemotes", data = {anim = "makeitrain"}, incar=1},
			["do_lift"] = {hotkey="7", label = "Ловить попутку", type = "dpemotes", data = {anim = "lift"}, incar=1},
			["do_namaste"] = {hotkey="8", label = "Намасте", type = "dpemotes", data = {anim = "namaste"}, incar=1},
		}
	},
	["festives"] = {
		hotkey = 'F',
		label = 'Действия c едой',
		items = {
			["f_burger"] = {hotkey="A", label = "Есть бургер", type = "dpemotes", data = {anim = "burger"}, incar=1},
			["f_donut"] = {hotkey="B", label = "Есть пончик", type = "dpemotes", data = {anim = "donut"}, incar=1},
			["f_bar"] = {hotkey="C", label = "Есть Батончик", type = "dpemotes", data = {anim = "egobar"}, incar=1},
			["f_sandwich"] = {hotkey="D", label = "Есть Сендвич", type = "dpemotes", data = {anim = "sandwich"}, incar=1},
			["f_whiskey"] = {hotkey="E", label = "Выпить виски", type = "dpemotes", data = {anim = "whiskey"}, incar=1},
			["f_champ"] = {hotkey="F", label = "Выпить шампанское", type = "dpemotes", data = {anim = "champagne"}, incar=1},
			["f_emptyglass"] = {hotkey="G", label = "Держать пустой бокал", type = "dpemotes", data = {anim = "flute"}, incar=1},
			["f_wine"] = {hotkey="H", label = "Выпить вино", type = "dpemotes", data = {anim = "wine"}, incar=1},
			["f_coffee1"] = {hotkey="I", label = "Выпить Кофе", type = "dpemotes", data = {anim = "coffee"}, incar=1},
			["f_coffee2"] = {hotkey="J", label = "Пить кофе", type = "event", data = {anim = "esx_animations:anim_coffee"}, incar=1},
			["f_cup"] = {hotkey="K", label = "Пить из стаканчика", type = "dpemotes", data = {anim = "cup"}, incar=1},
			["f_beer"] = {hotkey="L", label = "Пить пиво", type = "scenario", data = {anim = "WORLD_HUMAN_DRINKING"}},
			["f_beerparty"] = {hotkey="M", label = "Тусоваться с пивом", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING"}},
			["f_soda"] = {hotkey="N", label = "Выпить содовой", type = "dpemotes", data = {anim = "soda"}, incar=1},
		}
	},

	["greetings"] = {
		hotkey = 'G',
		label = 'Приветствия',
		items = {
			["greet_hello1"] = {hotkey="A", label = "Помахать", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello", upper=true, control=true}, incar=1},
			["greet_hello2"] = {hotkey="B", label = "Пожать руку", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a", upper=true, control=true}, incar=1},
			["greet_hug1"] = {hotkey="C", label = "Приобнять", type = "anim", data = {lib = "mp_ped_interaction", anim = "hugs_guy_a", upper=false, control=true}},
			["greet_hug2"] = {hotkey="D", label = "Обнять", type = "anim", data = {lib = "anim@amb@nightclub@djs@switch@bmad_djset_switchover@", anim = "bmad_out_soldix_in_a_bg_male1"}},
			["greet_kiss"] = {hotkey="E", label = "Поцеловать", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a", flag = 9}},
			["greet_bro1"] = {hotkey="F", label = "Братство", type = "anim", data = {lib = "anim@random@shop_clothes@watches", anim = "base", upper=true, control=true, flag = 9}, incar=1},
			["greet_salute"] = {hotkey="G", label = "Отдать честь", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute", stop_last_frame=true, upper=true, control=true,}, incar=1},
			["greet_bro2"] = {hotkey="H", label = "Бро", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@bro_love", anim = "bro_love"}},
			["greet_blowkiss1"] = {hotkey="I", label = "Воздушный поцелуй", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@blow_kiss", anim = "blow_kiss"}},
			["greet_blowkiss2"] = {hotkey="J", label = "Воздушный поцелуй Ж", type = "anim", data = {lib = "mini@hookers_sp", anim = "idle_a"}},
		}
	},

	["work"] = {
		hotkey = 'W',
		label = 'Работа',
		items = {
			["work_fish"] = {hotkey="A", label = "Рыбачить", type = "scenario", data = {anim = "world_human_stand_fishing"}},
			["work_investigate"] = {hotkey="B", label = "Искать улики", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f"}},
			["work_binoculars"] = {hotkey="C", label = "Смотреть в бинокль", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS"}},
			["work_gardener"] = {hotkey="D", label = "Копать", type = "scenario", data = {anim = "world_human_gardener_plant"}},
			["work_fixengine"] = {hotkey="E", label = "Чинить двигатель", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped", flag = 9}},
			["work_fixcar"] = {hotkey="F", label = "Чинить днище", type = "scenario", data = {anim = "WORLD_HUMAN_VEHICLE_MECHANIC"}},
			["work_weld"] = {hotkey="G", label = "Сварка", type = "scenario", data = {anim = "WORLD_HUMAN_WELDING"}},
			["work_mech"] = {hotkey="H", label = "Прикрутить", type = "anim", data = {lib = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", anim = "machinic_loop_mechandplayer", flag = 9}},
			["work_medkneel"] = {hotkey="I", label = "Осматривать", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL"}},
			["work_clean"] = {hotkey="J", label = "Протирать", type = "scenario", data = {anim = "world_human_maid_clean"}},
			["work_boxes"] = {hotkey="K", label = "Перекладывать ящики", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper", flag = 9}},
			["work_barman"] = {hotkey="L", label = "Налить рюмку", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b", flag = 9}},
			["work_photo"] = {hotkey="M", label = "Фотографировать", type = "dpemotes", data = {anim = "camera"}, incar=1},
			["work_clipboard"] = {hotkey="N", label = "Планшет", type = "dpemotes", data = {anim = "clipboard"}, incar=1},
			["work_notepad"] = {hotkey="O", label = "Блокнот", type = "dpemotes", data = {anim = "notepad"}, incar=1},
			["work_flash"] = {hotkey="P", label = "Светить фонарем М", type = "scenario", data = {anim = "WORLD_HUMAN_SECURITY_SHINE_TORCH"}},
			["work_carpark"] = {hotkey="Q", label = "Управление движением М", type = "scenario", data = {anim = "WORLD_HUMAN_CAR_PARK_ATTENDANT", flag = 9}},
			["work_hammer"] = {hotkey="R", label = "Молоток", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING"}},
			["work_drill"] = {hotkey="S", label = "Бурить ", type = "scenario", data = {anim = "WORLD_HUMAN_CONST_DRILL"}},
			["work_leaf"] = {hotkey="T", label = "Листодув М", type = "dpemotes", data = {anim = "leafblower"}},
			["work_bumfw"] = {hotkey="U", label = "Просить деньги М", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
			["work_mime"] = {hotkey="V", label = "Мим", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE"}},
			["work_tear"] = {hotkey="W", label = "Обрывать", type = "anim", data = {lib = "anim@amb@business@weed@weed_inspecting_lo_med_hi@", anim = "weed_crouch_checkingleaves_idle_01_inspectorfemale", flag = 9}},
			["work_safecr"] = {hotkey="X", label = "Взламывать Сейф", type = "anim", data = {lib = "mini@safe_cracking", anim = "idle_base", flag = 9}},
			["work_lockpick"] = {hotkey="Y", label = "Взламывать Замок", type = "anim", data = {lib = "low_int-0", anim = "ig_benny_dual-0", flag = 9}},
			["work_type1"] = {hotkey="Z", label = "Печатать", type = "dpemotes", data = {anim = "type4"}},
			["work_streetrace"] = {hotkey="1", label = "Старт стритрейсеров", type = "anim", data = {lib = "random@street_race", anim = "grid_girl_race_start", flag = 9}},
			["work_washhands"] = {hotkey="2", label = "Мыть руки", type = "anim", data = {lib = "missheist_agency3aig_23", anim = "urinal_sink_loop", flag = 9}},
			["work_mic"] = {hotkey="3", label = "Микрофон", type = "anim", data = {lib = "amb@world_human_aa_coffee@base", anim = "base", upper=true, control=true, flag = 9}, incar=1},
			["work_type2"] = {hotkey="4", label = "Печатать на компьютере", type = "anim", data = {lib = "maude_mcs_4-6", anim = "csb_maude_dual-6", upper=true, flag = 9}, incar=1},
			["work_medinspect"] = {hotkey="5", label = "Осмотр Доктора", type = "anim", data = {lib = "misscarsteal2fixer", anim = "confused_a", flag = 9}},
			["work_conjure"] = {hotkey="6", label = "Колдовать", type = "dpemotes", data = {anim = "mindcontrol2"}},
		}
	},

	["react"] = {
		hotkey = 'R',
		label = 'Реакции',
		items = {
			["react_cheer"] = {hotkey="A", label = "Хлопать", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING"}},
			["react_like"] = {hotkey="B", label = "Лайк", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06", upper=true, control=true}, incar=1},
			["react_fingerup"] = {hotkey="C", label = "Пальцы вверх", type = "anim", data = {lib = "anim@mp_player_intincarthumbs_upbodhi@ps@", anim = "idle_a", upper=true, control=true, flag = 9}, incar=1},
			["react_heyyou"] = {hotkey="D", label = "Эй ты", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_point", upper=true, control=true}, incar=1},
			["react_comehere"] = {hotkey="E", label = "Подойди", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_come_here_soft", upper=true, control=true}, incar=1},
			["react_bringiton"] = {hotkey="F", label = "Ну давай", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on", upper=true, control=true}, incar=1},
			["react_facepalm1"] = {hotkey="G", label = "Рукалицо", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm", upper=true, control=true}, incar=1},
			["react_facepalm2"] = {hotkey="H", label = "Рукалицо Ж", type = "anim", data = {lib = "random@robbery", anim = "stand_worried_female", upper=true, control=true, flag = 9}, incar=1},
			["react_carefulinspect"] = {hotkey="I", label = "Осторожно осмотреть", type = "anim", data = {lib = "oddjobs@assassinate@multi@", anim = "react_big_variations_a"}},
			["react_fright"] = {hotkey="J", label = "Испуг", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right", repeat_anim=true}},
			["react_damn"] = {hotkey="K", label = "Вот черт!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_damn", upper=true, control=true}, incar=1},
			["react_finger1"] = {hotkey="L", label = "Да пошли вы!", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter", upper=true, control=true}, incar=1},
			["react_wank"] = {hotkey="M", label = "Передернуть", type = "anim", data = {lib = "mp_player_int_upperwank", anim = "mp_player_int_wank_01", upper=true, control=true, flag = 9}, incar=1},
			["react_shoot"] = {hotkey="N", label = "Застрелиться", type = "anim", data = {lib = "mp_suicide", anim = "pistol", stop_last_frame=true}},
			["react_cool"] = {hotkey="O", label = "Это круто!", type = "anim", data = {lib = "anim@mp_player_intupperbanging_tunes", anim = "idle_a", upper=true, control=true, flag = 9}, incar=1},
			["react_rap"] = {hotkey="P", label = "Зачитать", type = "dpemotes", data = {anim = "danceupper"}, incar=1},
			["react_slowclap"] = {hotkey="Q", label = "Хлопки", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@slow_clap", anim = "slow_clap", upper=true, control=true, flag = 9}, incar=1},
			["react_dontknow"] = {hotkey="R", label = "Незнаю", type = "anim", data = {lib = "gestures@miss@dockssetup1", anim = "floyd_dh1_afac_01_g1"}},
			["react_think"] = {hotkey="S", label = "Подумай", type = "anim", data = {lib = "gestures@miss@fra_0", anim = "lamar_fkn0_cjae_01_g4", flag = 9}},
			["react_disappoint1"] = {hotkey="T", label = "Обида", type = "anim", data = {lib = "mini@hookers_sp", anim = "idle_reject"}},
			["react_why"] = {hotkey="U", label = "За что?", type = "anim", data = {lib = "random@car_thief@waiting_ig_4", anim = "idle_a"}},
			["react_heart"] = {hotkey="V", label = "Сердце прихватило", type = "anim", data = {lib = "rcmfanatic1out_of_breath", anim = "p_zero_tired_01", upper=true, flag = 9}, incar=1},
			["react_cry"] = {hotkey="W", label = "Плакать", type = "anim", data = {lib = "random@robbery", anim = "f_cower_01", flag = 9}},
			["react_admire"] = {hotkey="X", label = "Восхищение", type = "anim", data = {lib = "random@bus_tour_guide@idle_a", anim = "idle_b", flag = 9}},
			["react_disappoint2"] = {hotkey="Y", label = "Досада", type = "anim", data = {lib = "random@bicycle_thief@idle_a", anim = "idle_b", flag = 9}},
			["react_no"] = {hotkey="Z", label = "Неа!", type = "anim", data = {lib = "mini@prostitutestalk", anim = "street_argue_f_a", flag = 9}},
			["react_despair"] = {hotkey="1", label = "Отчаяние", type = "anim", data = {lib = "misscarsteal2car_stolen", anim = "chad_car_stolen_reaction", flag = 9}},
			["react_clown1"] = {hotkey="2", label = "Клоун1", type = "dpemotes", data = {anim = "clown"}},
			["react_clown2"] = {hotkey="3", label = "Клоун2", type = "dpemotes", data = {anim = "clown2"}},
			["react_cutthroat"] = {hotkey="4", label = "Угроза", type = "dpemotes", data = {anim = "cutthroat"}},
			["react_finger2"] = {hotkey="5", label = "Пошел ты", type = "dpemotes", data = {anim = "finger"}, incar=1},
			["react_peace1"] = {hotkey="6", label = "Мир", type = "dpemotes", data = {anim = "peace"}, incar=1},
			["react_peace2"] = {hotkey="7", label = "Мир 2", type = "dpemotes", data = {anim = "peace2"}, incar=1},
		}
	},

	["sports"] = {
		hotkey = 'S',
		label = 'Спорт',
		items = {
			["sport_muscleflex"] = {hotkey="A", label = "Показывать мускулы", type = "scenario", data = {anim = "WORLD_HUMAN_MUSCLE_FLEX"}},
			["sport_pushup"] = {hotkey="B", label = "Отжиматься", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base", flag = 9}},
			["sport_situp"] = {hotkey="C", label = "Качать пресс", type = "anim", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base", flag = 9}},
			["sport_yoga1"] = {hotkey="D", label = "Йога", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base_a", flag = 9}},
			["sport_yoga2"] = {hotkey="E", label = "Йога 2", type = "anim", data = {lib = "amb@world_human_yoga@female@base", anim = "base_c", flag = 9}},
			["sport_yoga3"] = {hotkey="F", label = "Йога 3", type = "dpemotes", data = {anim = "stretch4"}},
			["sport_unarmed"] = {hotkey="G", label = "Разминка перед дракой", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_e", flag = 9}},
			["sport_phys1"] = {hotkey="H", label = "Зарядка", type = "anim", data = {lib = "timetable@tracy@ig_5@idle_b", anim = "idle_e", flag = 9}},
			["sport_jogstand"] = {hotkey="I", label = "Бег на месте", type = "scenario", data = {anim = "WORLD_HUMAN_JOG_STANDING"}},
			["sport_chinup"] = {hotkey="J", label = "Турник", type = "scenario", data = {anim = "PROP_HUMAN_MUSCLE_CHIN_UPS"}},
			["sport_benchpress"] = {hotkey="K", label = "Жим лежа", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS"}},
			["sport_meditate1"] = {hotkey="L", label = "Медитация лотос", type = "anim", data = {lib = "rcmcollect_paperleadinout@", anim = "meditiate_idle", flag = 9}},
			["sport_meditate2"] = {hotkey="M", label = "Медитация стоя", type = "dpemotes", data = {anim = "statue3"}},
			["sport_phys2"] = {hotkey="N", label = "Разминка 1", type = "anim", data = {lib = "mini@triathlon", anim = "idle_a", flag = 9}},
			["sport_phys3"] = {hotkey="O", label = "Разминка 2", type = "anim", data = {lib = "mini@triathlon", anim = "idle_e", flag = 9}},
			["sport_backflip"] = {hotkey="P", label = "Бэкфлип", type = "dpemotes", data = {anim = "flip"}},
			["sport_frontflip"] = {hotkey="Q", label = "Фронтфлип", type = "dpemotes", data = {anim = "flip2"}},

		}
	},
	["sit"] = {
		hotkey = 'L',
		label = 'Сидеть/Лежать',
		items = {
			["sit_chill"] = {hotkey="A", label = "Отдыхать", type = "dpemotes", data = {anim = "chill"}},
			["sit_cloud"] = {hotkey="B", label = "Наблюдать за облаками", type = "dpemotes", data = {anim = "cloudgaze"}},
			["sit_shot"] = {hotkey="C", label = "Подстрелили", type = "dpemotes", data = {anim = "shot"}},
			["sit_curl"] = {hotkey="D", label = "Свернуться", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@lo_sofa@", anim = "lowsofa_dlg_fuckedup_laz", flag = 9}},
			["sit_layback1"] = {hotkey="E", label = "Лежать на спине", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
			["sit_layback2"] = {hotkey="F", label = "Лежать на спине 2", type = "dpemotes", data = {anim = "cloudgaze2"}},
			["sit_laystom1"] = {hotkey="G", label = "Лежать на животе", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE"}},
			["sit_laystom2"] = {hotkey="H", label = "Лежать на животе 2", type = "anim", data = {lib = "missarmenian2", anim = "drunk_loop", flag = 9}},
			["sit_laysider1"] = {hotkey="I", label = "Лежать на боку П", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_right_side@base", anim = "base", flag = 9}},
			["sit_laysidel1"] = {hotkey="J", label = "Лежать на боку Л", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_left_side@base", anim = "base", flag = 9}},
			["sit_laysidel2"] = {hotkey="K", label = "Лежать на боку Л2", type = "anim", data = {lib = "mini@cpr@char_b@cpr_def", anim = "cpr_intro", flag = 9}},
			["sit_layspread"] = {hotkey="L", label = "Лежать раскинувшись", type = "anim", data = {lib = "missarmenian2", anim = "corpse_search_exit_ped", flag = 9}},
			["sit_laydrunk"] = {hotkey="M", label = "Пьяный на земле", type = "anim", data = {lib = "timetable@amanda@drunk@idle_a", anim = "idle_pinot", flag = 9}},
			["sit_lean"] = {hotkey="N", label = "Сидеть облокотившись", type = "dpemotes", data = {anim = "sit2"}},
			["sit_kneehand"] = {hotkey="O", label = "Руки на коленях", type = "dpemotes", data = {anim = "sit5"}},
			["sit_detach"] = {hotkey="P", label = "Сидеть отрешенно", type = "anim", data = {lib = "anim@amb@business@bgen@bgen_no_work@", anim = "sit_phone_idle_03_nowork", flag = 9}},
			["sit_bored"] = {hotkey="Q", label = "Скучать", type = "anim", data = {lib = "anim@amb@business@cfm@cfm_machine_no_work@", anim = "sleep_cycle_v2_operator", flag = 9}},
			["sit_normal"] = {hotkey="R", label = "Сидеть", type = "scenario", data = {anim = "WORLD_HUMAN_PICNIC"}},
			["sit_knee"] = {hotkey="S", label = "Наблюдать на колене", type = "dpemotes", data = {anim = "kneel3"}},
			["sit_squat"] = {hotkey="T", label = "На кортах", type = "anim", data = {lib = "missheistdockssetup1ig_10@idle_a", anim = "talk_pipe_a_worker1", flag = 9}},
			["sit_squat2"] = {hotkey="U", label = "На кортах 2", type = "dpemotes", data = {anim = "kneel2"}},
			["sit_desperate1"] = {hotkey="V", label = "В отчаянии", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@lo_alone@", anim = "lowalone_base_laz", flag = 9}},
			["sit_desperate2"] = {hotkey="W", label = "В отчаянии 2", type = "dpemotes", data = {anim = "sitscared"}},
			-- ["sit_24"] = {hotkey="", label = "Сидеть тест", type = "scenario", data = {anim = "WORLD_HUMAN_SEAT_LEDGE"}},
			-- ["sit_25"] = {hotkey="", label = "Сидеть с пончиком", type = "scenario", data = {anim = "WORLD_HUMAN_SEAT_LEDGE_EATING"}},
			-- ["sit_26"] = {hotkey="", label = "Сидеть тест2", type = "scenario", data = {anim = "PROP_HUMAN_SEAT_ARMCHAIR"}},
		}
	},
	["stand"] = {
		hotkey = 'T',
		label = 'Стойки',
		items = {
			["stand_dancebar"] = {hotkey="A", label = "Пританцовывать бар", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds_transitions@", anim = "trans_li-mi_to_mi-hi_09_v1_male^3", flag = 9}},
			["stand_lure"] = {hotkey="B", label = "Завлекающая", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}},
			["stand_cop"] = {hotkey="C", label = "Коп", type = "scenario", data = {anim = "WORLD_HUMAN_COP_IDLES"}},
			["stand_guard"] = {hotkey="D", label = "Охрана", type = "scenario", data = {anim = "WORLD_HUMAN_GUARD_STAND"}},
			["stand_wait"] = {hotkey="E", label = "Ожидать", type = "scenario", data = {anim = "WORLD_HUMAN_STAND_IMPATIENT"}},
			["stand_waitf"] = {hotkey="F", label = "Ожидать Ж", type = "anim", data = {lib = "friends@fra@ig_1", anim = "base_idle", flag = 9}},
			["stand_lean1"] = {hotkey="G", label = "Облокотиться", type = "anim", data = {lib= "amb@prop_human_bum_shopping_cart@male@base", anim = "base",  flag = 9}},
			["stand_lean2"] = {hotkey="H", label = "Опереться спиной", type = "scenario", data = {anim = "world_human_leaning"}},
			["stand_think1"] = {hotkey="I", label = "Задуматься", type = "anim", data = {lib = "anim@amb@board_room@whiteboard@", anim = "think_01_amy_skater_01", upper=true, control=true, flag = 9}},
			["stand_lean3"] = {hotkey="J", label = "Опереться", type = "anim", data = {lib = "mp_safehousebeer@", anim = "base_drink", flag = 9}},
			["stand_leanlow"] = {hotkey="K", label = "Опереться низко", type = "anim", data = {lib = "anim@amb@board_room@diagram_blueprints@", anim = "idle_04_amy_skater_01", flag = 9}},
			["stand_bored1"] = {hotkey="L", label = "Скучать М", type = "anim", data = {lib = "anim@amb@business@cfid@cfid_photograph@", anim = "camera_fiddle_model", flag = 9}},
			["stand_bored2"] = {hotkey="M", label = "Скучать Ж", type = "anim", data = {lib = "anim@amb@nightclub@peds@", anim = "amb_world_human_hang_out_street_female_hold_arm_idle_b", flag = 9}},
			["stand_wall1"] = {hotkey="N", label = "Облокотиться спиной", type = "anim", data = {lib = "anim@amb@clubhouse@bar@bartender@", anim = "base_bartender", flag = 9}},
			["stand_cross1"] = {hotkey="O", label = "Скрестить руки 1", type = "anim", data = {lib = "anim@amb@nightclub@peds@", anim = "amb_world_human_hang_out_street_male_c_base", flag = 9}},
			["stand_cross2"] = {hotkey="P", label = "Скрестить руки 2", type = "anim", data = {lib = "anim@amb@nightclub@peds@", anim = "rcmme_amanda1_stand_loop_cop", flag = 9}},
			["stand_cross3"] = {hotkey="Q", label = "Скрестить руки 3", type = "anim", data = {lib = "random@shop_gunstore", anim = "_idle", flag = 9}},
			["stand_cross4"] = {hotkey="R", label = "Скрестить руки 4", type = "dpemotes", data = {anim = "crossarms"}},
			["stand_cross5"] = {hotkey="S", label = "Скрестить руки 5", type = "dpemotes", data = {anim = "crossarms3"}},
			["stand_crossf1"] = {hotkey="T", label = "Скрестить руки Ж", type = "anim", data = {lib = "amb@world_human_hang_out_street@female_arms_crossed@base", anim = "base", flag = 9}},
			["stand_crossf2"] = {hotkey="U", label = "Скрестить руки Ж2", type = "anim", data = {lib = "low_fun_mcs1-0", anim = "mp_m_g_vagfun_01^11_dual-0", flag = 9}},
			["stand_leanbar"] = {hotkey="V", label = "Опереться бар", type = "anim", data = {lib = "anim@amb@yacht@bow@female@variation_01@", anim = "idle_b", flag = 9}},
			["stand_handsbehind"] = {hotkey="W", label = "Руки за спиной", type = "anim", data = {lib = "ep_7_rcm-4", anim = "cs_jimmyboston_dual-4", upper=true, control=true, flag = 9}},
			["stand_handswaist"] = {hotkey="X", label = "Руки на поясе", type = "anim", data = {lib = "mmb_1_rcm-5", anim = "cs_joeminuteman_dual-5", upper=true, flag = 9}},
			["stand_verysad"] = {hotkey="Y", label = "Очень грустно", type = "anim", data = {lib = "oddjobs@bailbond_hobodepressed", anim = "idle_a", flag = 9}},
			["stand_spread"] = {hotkey="Z", label = "Расставить руки", type = "anim", data = {lib = "martin_1_int-1", anim = "cs_martinmadrazo_dual-1", flag = 9}},
			["stand_asocial"] = {hotkey="1", label = "Зажатая Ж", type = "anim", data = {lib = "low_fun_mcs1-0", anim = "mp_m_g_vagfun_01^12_dual-0", flag = 9}},
			["stand_wall2"] = {hotkey="2", label = "Спиной к стене скрестить руки", type = "anim", data = {lib = "impexp_int_l1-10", anim = "mp_m_waremech_01_dual-10", flag = 9}},
			["stand_think2"] = {hotkey="3", label = "Думать", type = "anim", data = {lib = "misscarsteal4@aliens", anim = "rehearsal_base_idle_director"}},
			["stand_think3"] = {hotkey="4", label = "Думать 2", type = "dpemotes", data = {anim = "think2"}},
			["stand_hanghook"] = {hotkey="5", label = "Висеть на крюке", type = "anim", data = {lib = "mic_2_mcs_1-0", anim = "player_zero_dual-0", flag = 9}},
			["stand_leanside"] = {hotkey="6", label = "Опереться боком", type = "anim", data = {lib = "misscarsteal1car_1_ext_leadin", anim = "base_driver1", flag = 9}},
			["stand_leahhand"] = {hotkey="7", label = "Опереться рукой", type = "anim", data = {lib = "misscarstealfinale", anim = "packer_idle_1_trevor", flag = 9}},
			["stand_leanelbow"] = {hotkey="8", label = "Опереться локтем", type = "anim", data = {lib = "misscarstealfinalecar_5_ig_1", anim = "waitloop_lamar", flag = 9}},
			["stand_hero"] = {hotkey="9", label = "Супергерой", type = "dpemotes", data = {anim = "superhero"}},
		}

	},
	["attitudem"] = {
		hotkey = 'O',
		label = 'Походки М',
		items = {
			["gait_normal"] = {hotkey="A", label = "Обычная М", type = "attitude", data = {lib = "move_m@shocked@a", anim = "move_m@shocked@a"}, incar=1},
			["gait_confident"] = {hotkey="B", label = "Сдержанная", type = "attitude", data = {lib = "move_m@confident", anim = "move_m@confident"}, incar=1},
			["gait_sad"] = {hotkey="C", label = "Депрессивная", type = "attitude", data = {lib = "move_m@sad@a", anim = "move_m@sad@a"}, incar=1},
			["gait_business"] = {hotkey="D", label = "Спокойная", type = "attitude", data = {lib = "move_m@business@a", anim = "move_m@business@a"}, incar=1},
			["gait_brave"] = {hotkey="E", label = "Уверенная", type = "attitude", data = {lib = "move_m@brave@a", anim = "move_m@brave@a"}, incar=1},
			["gait_casual"] = {hotkey="F", label = "Задумчивая", type = "attitude", data = {lib = "move_m@casual@a", anim = "move_m@casual@a"}, incar=1},
			["gait_fat"] = {hotkey="G", label = "Пухлая", type = "attitude", data = {lib = "move_m@fat@a", anim = "move_m@fat@a"}, incar=1},
			["gait_hipster"] = {hotkey="H", label = "Хипстерская", type = "attitude", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a"}, incar=1},
			["gait_injured"] = {hotkey="I", label = "Хромая", type = "attitude", data = {lib = "move_m@injured", anim = "move_m@injured"}, incar=1},
			["gait_casual"] = {hotkey="J", label = "Ритмичная", type = "attitude", data = {lib = "move_m@casual@e", anim = "move_m@casual@e"}, incar=1},
			["gait_thread"] = {hotkey="K", label = "Угрожающая", type = "attitude", data = {lib = "move_characters@franklin@fire", anim = "move_characters@franklin@fire"}, incar=1},
			["gait_brave"] = {hotkey="L", label = "Грозная", type = "attitude", data = {lib = "move_m@brave@b", anim = "move_m@brave@b"}, incar=1},
			["gait_hovo"] = {hotkey="M", label = "Выпивший", type = "attitude", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a"}, incar=1},
			["gait_depress"] = {hotkey="N", label = "Пьяная", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a"}, incar=1},
			["gait_verydrunk"] = {hotkey="O", label = "В стельку", type = "attitude", data = {lib = "move_m@drunk@verydrunk", anim = "move_m@drunk@verydrunk"}, incar=1},
			["gait_alpha"] = {hotkey="P", label = "Альфа", type = "attitude", data = {lib = "move_p_m_zero_slow", anim = "move_p_m_zero_slow"}, incar=1},
			["gait_muscle"] = {hotkey="Q", label = "Гордая", type = "attitude", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a"}, incar=1},
			["gait_shady"] = {hotkey="R", label = "В развалку", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a"}, incar=1},
			["gait_tired"] = {hotkey="S", label = "Уставшая", type = "attitude", data = {lib = "move_m@buzzed", anim = "move_m@buzzed"}, incar=1},
			["gait_verytired"] = {hotkey="T", label = "Очень уставшая", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a"}, incar=1},
			["gait_hurry1"] = {hotkey="U", label = "Спешащая М1", type = "attitude", data = {lib = "move_m@hurry@a", anim = "move_m@hurry@a"}, incar=1},
			["gait_hurry2"] = {hotkey="V", label = "Спешащая М2", type = "attitude", data = {lib = "move_m@hurry_butch@a", anim = "move_m@hurry_butch@a"}, incar=1},
			["gait_quick"] = {hotkey="W", label = "Бегом", type = "attitude", data = {lib = "move_m@quick", anim = "move_m@quick"}, incar=1},
			["gait_swagger"] = {hotkey="X", label = "На стиле", type = "attitude", data = {lib = "move_m@swagger", anim = "move_m@swagger"}, incar=1},
			["gait_battle"] = {hotkey="Y", label = "Боевая", type = "attitude", data = {lib = "move_action@generic@core", anim = "move_action@generic@core"}, incar=1},
			["gait_stagger"] = {hotkey="Z", label = "Шатающаяся", type = "attitude", data = {lib = "move_characters@orleans@core@", anim = "move_characters@orleans@core@"}, incar=1},
			["gait_jaded"] = {hotkey="1", label = "Измученная", type = "attitude", data = {lib = "move_m@drunk@a", anim = "move_m@drunk@a"}, incar=1},
			["gait_moddrunk"] = {hotkey="2", label = "Без сил", type = "attitude", data = {lib = "move_m@drunk@moderatedrunk", anim = "move_m@drunk@moderatedrunk"}, incar=1},
			["gait_dance"] = {hotkey="3", label = "Пританцовывая М", type = "attitude", data = {lib = "move_m@money", anim = "move_m@money"}, incar=1},
			["gait_pathetic"] = {hotkey="4", label = "Пафосная", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a"}, incar=1},
			["gait_pimp"] = {hotkey="5", label = "Сутенерская", type = "attitude", data = {lib = "move_m@swagger", anim = "move_m@swagger"}, incar=1},
		}
	},

	["attitudef"] = {
		hotkey = 'P',
		label = 'Походки Ж',
		items = {
			["gaitf_normal"] = {hotkey="A", label = "Обычная Ж", type = "attitude", data = {lib = "move_f@generic", anim = "move_f@generic"}, incar=1},
			["gaitf_heels"] = {hotkey="B", label = "Сдержанная Ж", type = "attitude", data = {lib = "move_f@heels@c", anim = "move_f@heels@c"}, incar=1},
			["gaitf_depress"] = {hotkey="C", label = "Депрессивная Ж", type = "attitude", data = {lib = "move_f@depressed@a", anim = "move_f@depressed@a"}, incar=1},
			["gaitf_groove"] = {hotkey="D", label = "Ритмичная Ж", type = "attitude", data = {lib = "anim@move_f@grooving@", anim = "anim@move_f@grooving@"}, incar=1},
			["gaitf_tough"] = {hotkey="E", label = "Деловая Ж", type = "attitude", data = {lib = "move_f@tough_guy@", anim = "move_f@tough_guy@"}, incar=1},
			["gaitf_arrogant"] = {hotkey="F", label = "В развалку Ж", type = "attitude", data = {lib = "move_f@arrogant@a", anim = "move_f@arrogant@a"}, incar=1},
			["gaitf_maneater"] = {hotkey="G", label = "На стиле Ж", type = "attitude", data = {lib = "move_f@maneater", anim = "move_f@maneater"}, incar=1},
			["gaitf_fat"] = {hotkey="H", label = "Пухлая Ж", type = "attitude", data = {lib = "move_f@fat@a", anim = "move_f@fat@a"}, incar=1},
			["gaitf_femme"] = {hotkey="I", label = "От бедра Ж", type = "attitude", data = {lib = "move_f@femme@", anim = "move_f@femme@"}, incar=1},
			["gaitf_sassy"] = {hotkey="J", label = "Спешащая Ж", type = "attitude", data = {lib = "move_f@sassy", anim = "move_f@sassy"}, incar=1},
			["gaitf_hurry"] = {hotkey="K", label = "Спешащая Ж2", type = "attitude", data = {lib = "move_f@hurry@a", anim = "move_f@hurry@a"}, incar=1},
			["gaitf_sad"] = {hotkey="L", label = "Грустная Ж", type = "attitude", data = {lib = "move_f@sad@a", anim = "move_f@sad@a"}, incar=1},
			["gaitf_mfemme"] = {hotkey="M", label = "Свободная Ж", type = "attitude", data = {lib = "move_m@femme@", anim = "move_m@femme@"}, incar=1},
		}
	},

	["dance"] = {
		hotkey = 'D',
		label = 'Танцы',
		items = {
			["dance_shuffle"] = {hotkey="A", label = "Шафл", type = "dpemotes", data = {anim = "dancesilly7"}},
			["dance_tap"] = {hotkey="B", label = "Чечетка", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag", flag = 9}},
			["dance_whirl"] = {hotkey="C", label = "Водоворот", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_ig", anim = "dance_loop_tao", flag = 9}},
			["dance_unislow1"] = {hotkey="D", label = "Единорог медленный 1", type = "dpemotes", data = {anim = "unicorn1"}},
			["dance_unislow2"] = {hotkey="E", label = "Единорог медленный 2", type = "dpemotes", data = {anim = "unicorn6"}},
			["dance_unifast1"] = {hotkey="F", label = "Единорог активный 1", type = "dpemotes", data = {anim = "unicorn2"}},
			["dance_unifast2"] = {hotkey="G", label = "Единорог активный 2", type = "dpemotes", data = {anim = "unicorn3"}},
			["dance_unifast3"] = {hotkey="H", label = "Единорог активный 3", type = "dpemotes", data = {anim = "unicorn4"}},
			["dance_unifast4"] = {hotkey="I", label = "Единорог активный 4", type = "dpemotes", data = {anim = "unicorn5"}},
			["dance_glowstick1"] = {hotkey="J", label = "Светящиеся палки 1", type = "dpemotes", data = {anim = "danceglowstick"}, incar=1},
			["dance_glowstick2"] = {hotkey="K", label = "Светящиеся палки 2", type = "dpemotes", data = {anim = "danceglowstick2"}},
			["dance_glowstick3"] = {hotkey="L", label = "Светящиеся палки 3", type = "dpemotes", data = {anim = "danceglowstick3"}},
		}
	},

	["dancef"] = {
		hotkey = 'E',
		label = 'Танцы Ж',
		items = {
			["dancef_style"] = {hotkey="A", label = "Стильная", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "hi_dance_crowd_09_v2_female^1", flag = 9}},
			["dancef_easy1"] = {hotkey="B", label = "Легкий денс", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "hi_dance_crowd_09_v2_female^2", flag = 9}},
			["dancef_flex"] = {hotkey="C", label = "На флексе", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "hi_dance_crowd_09_v2_female^3", flag = 9}},
			["dancef_tired"] = {hotkey="D", label = "Уставшая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "hi_dance_crowd_09_v2_female^4", flag = 9}},
			["dancef_star"] = {hotkey="E", label = "Звездная", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "hi_dance_crowd_15_v1_female^1", flag = 9}},
			["dancef_onwave"] = {hotkey="F", label = "На волне 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "mi_dance_crowd_11_v1_female^3", flag = 9}},
			["dancef_drunk"] = {hotkey="G", label = "Пьяненькая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "mi_dance_crowd_15_v2_female^3", flag = 9}},
			["dancef_energy1"] = {hotkey="H", label = "Энергичная", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "hi_dance_crowd_11_v1_female^1", flag = 9}},
			["dancef_energy2"] = {hotkey="I", label = "Энергичная 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@", anim = "mi_dance_crowd_17_v2_female^1", flag = 9}},
			["dancef_energy3"] = {hotkey="J", label = "Энергичная 3", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_13_v2_female^1", flag = 9}},
			["dancef_playful1"] = {hotkey="K", label = "Игривая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v2_female^1", flag = 9}},
			["dancef_casual"] = {hotkey="L", label = "Обычный", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v2_female^2", flag = 9}},
			["dancef_playful2"] = {hotkey="M", label = "Игривая 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v2_female^3", flag = 9}},
			["dancef_casual2"] = {hotkey="N", label = "Обычный 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_11_v1_female^3", flag = 9}},
			["dancef_gowild"] = {hotkey="O", label = "В отрыв", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_13_v2_female^2", flag = 9}},
			["dancef_easy2"] = {hotkey="P", label = "Легкая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_13_v2_female^5", flag = 9}},
			["dancef_happy"] = {hotkey="Q", label = "Веселая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_13_v2_male^5", flag = 9}},
			["dancef_wavy1"] = {hotkey="R", label = "Волнистая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_17_v2_female^1", flag = 9}},
			["dancef_wavy2"] = {hotkey="S", label = "Волнистая 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "mi_dance_facedj_15_v1_female^1", flag = 9}},
			["dancef_wavy3"] = {hotkey="T", label = "Волнистая 3", type = "dpemotes", data = {anim = "danceslow2"}},
			["dancef_allure1"] = {hotkey="U", label = "Соблазнительная", type = "anim", data = {lib = "anim@amb@nightclub@peds@", anim = "mini_strip_club_private_dance_idle_priv_dance_idle", flag = 9}},
			["dancef_dream"] = {hotkey="V", label = "Мечтательная", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_center", flag = 9}},
			["dancef_cute"] = {hotkey="W", label = "Няшная", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "med_center", flag = 9}},
			["dancef_allure2"] = {hotkey="X", label = "Заманивающая", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_center_down", flag = 9}},
			["dancef_smooth"] = {hotkey="Y", label = "Плавная", type = "dpemotes", data = {anim = "dance5"}},

			-- ["dancef_26"] = {hotkey="", label = "Единорог медленный 1", type = "dpemotes", data = {anim = "unicorn1"}},
			-- ["dancef_27"] = {hotkey="", label = "Единорог медленный 2", type = "dpemotes", data = {anim = "unicorn6"}},
			-- ["dancef_28"] = {hotkey="", label = "Единорог активный 1", type = "dpemotes", data = {anim = "unicorn2"}},
			-- ["dancef_29"] = {hotkey="", label = "Единорог активный 2", type = "dpemotes", data = {anim = "unicorn3"}},
			-- ["dancef_30"] = {hotkey="", label = "Единорог активный 3", type = "dpemotes", data = {anim = "unicorn4"}},
			-- ["dancef_31"] = {hotkey="", label = "Единорог активный 4", type = "dpemotes", data = {anim = "unicorn5"}},
		}
	},

	["dancem"] = {
		hotkey = 'C',
		label = 'Танцы M',
		items = {
			["dancem_warmup"] = {hotkey="A", label = "Разогрев", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v2_male^6", flag = 9}},
			["dancem_aware"] = {hotkey="B", label = "В теме", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_13_v2_male^6", flag = 9}},
			["dancem_shake"] = {hotkey="C", label = "Качает", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center_up", flag = 9}},
			["dancem_woundup1"] = {hotkey="D", label = "Заводила", type = "anim", data = {lib = "mini@strip_club@idles@dj@idle_04", anim = "idle_04", flag = 9}},
			["dancem_relaxed"] = {hotkey="E", label = "Расслабленная", type = "anim", data = {lib = "anim@amb@nightclub@dancers@black_madonna_entourage@", anim = "hi_dance_facedj_09_v2_male^5", flag = 9}},
			["dancem_onwave"] = {hotkey="F", label = "Волна", type = "anim", data = {lib = "anim@amb@nightclub@dancers@dixon_entourage@", anim = "mi_dance_facedj_15_v1_male^4", flag = 9}},
			["dancem_style1"] = {hotkey="G", label = "На стиле", type = "anim", data = {lib = "anim@amb@nightclub@dancers@podium_dancers@", anim = "hi_dance_facedj_17_v2_male^5", flag = 9}},
			["dancem_gibberish"] = {hotkey="H", label = "Легкий расколбас", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center", flag = 9}},
			["dancem_stomp"] = {hotkey="I", label = "Топ-топ", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim = "high_center", flag = 9}},
			["dancem_lowclap"] = {hotkey="J", label = "Низкий хлоп ", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_13_v2_male^2", flag = 9}},
			["dancem_style2"] = {hotkey="K", label = "Стильная 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_female^6", flag = 9}},
			["dancem_away1"] = {hotkey="L", label = "Уносящая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_male^2", flag = 9}},
			["dancem_away2"] = {hotkey="M", label = "Уносящая 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v2_female^4", flag = 9}},
			["dancem_rampant"] = {hotkey="N", label = "Безудержанная", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_male^4", flag = 9}},
			["dancem_flex"] = {hotkey="O", label = "Флексовая", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "mi_dance_facedj_09_v1_male^4", flag = 9}},
			["dancem_easy"] = {hotkey="P", label = "Легкий", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "mi_dance_facedj_11_v2_male^5", flag = 9}},
			["dancem_woundup2"] = {hotkey="Q", label = "Заводила 2", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_17_spiderman_laz", flag = 9}},
			["dancem_pulpfict"] = {hotkey="R", label = "Криминальное чтиво", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_15_flyingv_laz", flag = 9}},
			["dancem_robot"] = {hotkey="S", label = "Робот", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_15_robot_laz", flag = 9}},
			["dancem_whirl"] = {hotkey="T", label = "Закружило", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_15_shimmy_laz", flag = 9}},
			["dancem_disco1"] = {hotkey="U", label = "Диско", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_17_crotchgrab_laz", flag = 9}},
			["dancem_disco2"] = {hotkey="V", label = "Диско М", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_17_teapotthrust_laz", flag = 9}},
			["dancem_forced"] = {hotkey="W", label = "Принудительная", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "low_center", flag = 9}},
			["dancem_tired"] = {hotkey="X", label = "Уставшая", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "low_center", flag = 9}},
			["dancem_gang"] = {hotkey="Y", label = "Гэнгста", type = "dpemotes", data = {anim = "dance8"}},


		}
	},
-- {
-- 	name  = 'anims',
-- 	label = 'testanim',
-- 	items = {

-- 		["test_1"] = {hotkey="", label = "Приват 1", type = "anim", data = {lib = "family_4_mcs_2-12", anim = "cs_tracydisanto_dual-12", flag = 9}},
-- 		["test_2"] = {hotkey="", label = "Приват 2", type = "anim", data = {lib = "family_4_mcs_2-14", anim = "cs_tracydisanto_dual-14", flag = 9}},
-- 		["test_3"] = {hotkey="", label = "Приват 3", type = "anim", data = {lib = "friends@", anim = "pickupwait", flag = 9}},

-- 		["test_4"] = {hotkey="", label = "Приват 5", type = "anim", data = {lib = "friends@fra@ig_1", anim = "impatient_idle_a", flag = 9}},
-- 		["test_5"] = {hotkey="", label = "Приват 6", type = "anim", data = {lib = "friends@fra@ig_1", anim = "impatient_idle_a", flag = 9}},

-- 		["test_6"] = {hotkey="", label = "Приват 8", type = "anim", data = {lib = "gestures@miss@dockssetup1", anim = "floyd_dh1_atab_01_g1", flag = 9}},
-- 		["test_7"] = {hotkey="", label = "Приват 9", type = "anim", data = {lib = "gestures@miss@dockssetup1", anim = "floyd_dh1_atag_01_g2", flag = 9}},


-- 		["test_8"] = {hotkey="", label = "Приват 14", type = "anim", data = {lib = "mini@cpr@char_a@cpr_str", anim = "cpr_cpr_to_kol", flag = 9}},

-- 		["test_9"] = {hotkey="", label = "Приват 16", type = "anim", data = {lib = "mini@hookers_sp", anim = "idle_wait", flag = 9}},
-- 		["test_10"] = {hotkey="", label = "Приват 17", type = "anim", data = {lib = "mini@hookers_sp", anim = "ilde_d", flag = 9}},
-- 		["test_11"] = {hotkey="", label = "Приват 18", type = "anim", data = {lib = "missfam2_washing_face", anim = "michael_washing_face", flag = 9}},



-- 	}
-- },

	["strip"] = {
		hotkey = 'Z',
		name  = 'misc',
		label = 'Стриптиз',
		items = {
			["strip_private1"] = {hotkey="A", label = "Приват 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p2", anim = "ld_girl_a_song_a_p2_f", flag = 9}},
			["strip_private2"] = {hotkey="B", label = "Приват 2", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p3", anim = "ld_girl_a_song_a_p3_f", flag = 9}},
			["strip_lure1"] = {hotkey="C", label = "Завлекающий 1", type = "anim", data = {lib = "mini@strip_club@private_dance@part1", anim = "priv_dance_p1", flag = 9}},
			["strip_lure2"] = {hotkey="D", label = "Завлекающий 2", type = "anim", data = {lib = "mini@strip_club@idles@stripper", anim = "stripper_idle_02", flag = 9}},
			["strip_1"] = {hotkey="E", label = "Стриптиз 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim = "ld_girl_a_song_a_p1_f", flag = 9}},
			["strip_2"] = {hotkey="F", label = "Стриптиз 2", type = "anim", data = {lib = "mini@strip_club@private_dance@part2", anim = "priv_dance_p2", flag = 9}},
			["strip_3"] = {hotkey="G", label = "Стриптиз 3", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3", flag = 9}},
			["strip_4"] = {hotkey="H", label = "Стриптиз 4", type = "anim", data = {lib = "mp_am_stripper", anim = "lap_dance_girl", flag = 9}},
			["strip_pylon1"] = {hotkey="I", label = "У шеста 1", type = "anim", data = {lib = "mini@strip_club@pole_dance@pole_dance1", anim = "pd_dance_01", flag = 9}},
			["strip_pylon2"] = {hotkey="J", label = "У шеста 2", type = "anim", data = {lib = "mini@strip_club@pole_dance@pole_dance2", anim = "pd_dance_02", flag = 9}},
			["strip_pylon3"] = {hotkey="K", label = "У шеста 3", type = "anim", data = {lib = "mini@strip_club@pole_dance@pole_dance3", anim = "pd_dance_03", flag = 9}},
		}
	},

	["xxx"] = {
		hotkey = 'X',
		label = '18+',
		items = {
			["xxx_bj1"] = {hotkey="A", label = "Минет", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_hooker", flag = 9}},
			["xxx_wall"] = {hotkey="B", label = "У стенки", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_punter"}},
			["xxx_back"] = {hotkey="C", label = "Сзади", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "shagloop_pimp", flag = 9}},
			["xxx_bj2"] = {hotkey="D", label = "Минет в машине Ж", type = "anim", data = {lib = "oddjobs@towing", anim = "f_blow_job_loop", in_vehicle=true, flag = 9}, incar=2},
			["xxx_car1"] = {hotkey="E", label = "За рулем 1", type = "anim", data = {lib = "oddjobs@towing", anim = "m_blow_job_loop", in_vehicle=true, flag = 9}, incar=2},
			["xxx_car2"] = {hotkey="F", label = "За рулем 2", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_player", in_vehicle=true, repeat_anim=true, flag = 9}, incar=2},
			["xxx_car3"] = {hotkey="G", label = "За рулем 3", type = "anim", data = {lib = "oddjobs@assassinate@vice@sex", anim = "frontseat_carsex_loop_m", flag = 9}, incar=2},
			["xxx_car4"] = {hotkey="H", label = "В машине сверху Ж", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_female", in_vehicle=true, repeat_anim=true, flag = 9}, incar=2},
			["xxx_car5"] = {hotkey="I", label = "В машине сверху Ж2", type = "anim", data = {lib = "oddjobs@assassinate@vice@sex", anim = "frontseat_carsex_loop_f", flag = 9}, incar=2},
			["xxx_escort"] = {hotkey="J", label = "Эскорт", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", flag = 9}},
			["xxx_twerk"] = {hotkey="K", label = "Тверк", type = "dpemotes", data = {anim = "twerk"}},
		}
	},
	["animals"] = {
		hotkey = 'Y',
		label = 'Животные',
		items = {
			-- ------------------------ЖИВОТНЫЕ
			["animal_catsleep"] = {hotkey="A", label = "Кошка свернуться клубочком", type = "scenario", data = {anim = "WORLD_CAT_SLEEPING_GROUND"}},
			["animal_dogfind"] = {hotkey="B", label = "Cобака найти что-то", type = "scenario", data = {anim = "WORLD_DOG_BARKING_ROTTWEILER"}},
			["animal_dogsit"] = {hotkey="C", label = "Cобака сесть", type = "scenario", data = {anim = "WORLD_DOG_SITTING_ROTTWEILER"}},
			["animal_hawkfeed"] = {hotkey="D", label = "Орел кушать", type = "scenario", data = {anim = "WORLD_CHICKENHAWK_FEEDING"}},
			["animal_hawkstand"] = {hotkey="E", label = "Орел отдыхать", type = "scenario", data = {anim = "WORLD_CHICKENHAWK_STANDING"}},
			["animal_crowfeed"] = {hotkey="F", label = "Ворон кушать", type = "scenario", data = {anim = "WORLD_CROW_FEEDING"}},
			["animal_crowstand"] = {hotkey="G", label = "Ворон отдыхать", type = "scenario", data = {anim = "WORLD_CROW_STANDING"}},
			["animal_deer"] = {hotkey="H", label = "Олень", type = "scenario", data = {anim = "WORLD_DEER_GRAZING"}},
			["animal_boar"] = {hotkey="I", label = "Кабан", type = "scenario", data = {anim = "WORLD_BOAR_GRAZING"}},
			["animal_cow"] = {hotkey="J", label = "Корова", type = "scenario", data = {anim = "WORLD_COW_GRAZING"}},
			["animal_cormorant"] = {hotkey="K", label = "Пеликан", type = "scenario", data = {anim = "WORLD_CORMORANT_STANDING"}},
			["animal_rabbit"] = {hotkey="L", label = "Кролик", type = "scenario", data = {anim = "WORLD_RABBIT_EATING"}},
			["animal_pig"] = {hotkey="M", label = "Свинья", type = "scenario", data = {anim = "WORLD_PIG_GRAZING"}},
			-- ["animal_4"] = {hotkey="", label = "69", type = "scenario", data = {anim = "WORLD_CAT_SLEEPING_LEDGE"}},
			-- ["animal_5"] = {hotkey="", label = "Койот выть", type = "scenario", data = {anim = "WORLD_COYOTE_HOWL"}},
			-- ["animal_6"] = {hotkey="", label = "72", type = "scenario", data = {anim = "WORLD_COYOTE_REST"}},
			-- ["animal_7"] = {hotkey="", label = "73", type = "scenario", data = {anim = "WORLD_COYOTE_WANDER"}},
			-- ["animal_18"] = {hotkey="", label = "Cобака ", type = "scenario", data = {anim = "WORLD_DOG_BARKING_RETRIEVER"}},
			-- ["animal_19"] = {hotkey="", label = "Cобака", type = "scenario", data = {anim = "WORLD_DOG_BARKING_SHEPHERD"}},
			-- ["animal_20"] = {hotkey="", label = "Cобака", type = "scenario", data = {anim = "WORLD_DOG_SITTING_RETRIEVER"}},
			-- ["animal_21"] = {hotkey="", label = "Cобака", type = "scenario", data = {anim = "WORLD_DOG_SITTING_SHEPHERD"}},
			-- ["animal_22"] = {hotkey="", label = "Cобака", type = "scenario", data = {anim = "WORLD_DOG_BARKING_SMALL"}},
			-- ["animal_23"] = {hotkey="", label = "Cобака", type = "scenario", data = {anim = "WORLD_DOG_SITTING_SMALL"}},
			-- ["animal_24"] = {hotkey="", label = "88", type = "scenario", data = {anim = "WORLD_FISH_IDLE"}},
			-- ["animal_25"] = {hotkey="", label = "89", type = "scenario", data = {anim = "WORLD_GULL_FEEDING"}},
			-- ["animal_26"] = {hotkey="", label = "90", type = "scenario", data = {anim = "WORLD_GULL_STANDING"}},
			-- ["animal_27"] = {hotkey="", label = "91", type = "scenario", data = {anim = "WORLD_HEN_PECKING"}},
			-- ["animal_28"] = {hotkey="", label = "92", type = "scenario", data = {anim = "WORLD_HEN_STANDING"}},
			-- ["animal_29"] = {hotkey="", label = "93", type = "scenario", data = {anim = "WORLD_MOUNTAIN_LION_REST"}},
			-- ["animal_30"] = {hotkey="", label = "94", type = "scenario", data = {anim = "WORLD_MOUNTAIN_LION_WANDER"}}
			-- ["animal_31"] = {hotkey="", label = "96", type = "scenario", data = {anim = "WORLD_PIGEON_FEEDING"}},
			-- ["animal_32"] = {hotkey="", label = "97", type = "scenario", data = {anim = "WORLD_PIGEON_STANDING"}},

			-- ["animal_33"] = {hotkey="", label = "A99", type = "scenario", data = {anim = "WORLD_SHARK_SWIM"}},
		}
 },

--  {
-- 	name  = 'test',
-- 	label = 'Тест',
-- 	items = {
-- 		-- ------------------------ЖИВОТНЫЕ
		-- ["test2_1"] = {hotkey="", label = "Разминка 1", type = "anim", data = {lib = "mini@triathlon", anim = "idle_a", flag = 9}},
		-- ["test2_2"] = {hotkey="", label = "Разминка 2", type = "anim", data = {lib = "mini@triathlon", anim = "idle_e", flag = 9}},

		-- ["test2_3"] = {hotkey="", label = "Лежать раскинувшись", type = "anim", data = {lib = "missarmenian2", anim = "corpse_search_exit_ped", flag = 9}},
		-- ["test2_4"] = {hotkey="", label = "Лежать на животе 2", type = "anim", data = {lib = "missarmenian2", anim = "drunk_loop", flag = 9}},

		-- ["test2_5"] = {hotkey="", label = "Отчаяние", type = "anim", data = {lib = "misscarsteal2car_stolen", anim = "chad_car_stolen_reaction", flag = 9}},


		-- ["test2_6"] = {hotkey="", label = "Думать", type = "anim", data = {lib = "misscarsteal4@aliens", anim = "rehearsal_base_idle_director"}},
		-- ["test2_7"] = {hotkey="", label = "Висеть на крюке", type = "anim", data = {lib = "mic_2_mcs_1-0", anim = "player_zero_dual-0", flag = 9}},
		-- ["test2_8"] = {hotkey="", label = "Опереться боком", type = "anim", data = {lib = "misscarsteal1car_1_ext_leadin", anim = "base_driver1", flag = 9}},
		-- ["test2_9"] = {hotkey="", label = "Опереться рукой", type = "anim", data = {lib = "misscarstealfinale", anim = "packer_idle_1_trevor", flag = 9}},
		-- ["test2_10"] = {hotkey="", label = "Опереться локтем", type = "anim", data = {lib = "misscarstealfinalecar_5_ig_1", anim = "waitloop_lamar", flag = 9}},
-- 	}
-- },

}
