ESX = nil
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

ESX.RegisterUsableItem('umbrella', function(source)
  TriggerClientEvent("dpemotes:emote", "umbrella")
end)
ESX.RegisterUsableItem('flowers', function(source)
  TriggerClientEvent("dpemotes:emote", "bouquet")
end)
ESX.RegisterUsableItem('teddy', function(source)
  TriggerClientEvent("dpemotes:emote", "teddy")
end)
ESX.RegisterUsableItem('backpack', function(source)
  TriggerClientEvent("dpemotes:emote", "backpack")
end)
ESX.RegisterUsableItem('guitar1', function(source)
  TriggerClientEvent("dpemotes:emote", "guitar")
end)
ESX.RegisterUsableItem('guitar2', function(source)
  TriggerClientEvent("dpemotes:emote", "guitarelectric2")
end)
ESX.RegisterUsableItem('suitcase2', function(source)
  TriggerClientEvent("dpemotes:emote", "suitcase2")
end)
ESX.RegisterUsableItem('suitcase3', function(source)
  TriggerClientEvent("dpemotes:emote", "suitcase")
end)
