ESX = nil
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

ESX.RegisterUsableItem('umbrella', function(source)
  TriggerClientEvent("dpemotes:emote", source, "umbrella")
end)
ESX.RegisterUsableItem('flowers', function(source)
  TriggerClientEvent("dpemotes:emote", source, "bouquet")
end)
ESX.RegisterUsableItem('teddy', function(source)
  TriggerClientEvent("dpemotes:emote", source, "teddy")
end)
ESX.RegisterUsableItem('backpack', function(source)
  TriggerClientEvent("dpemotes:emote", source, "backpack")
end)
ESX.RegisterUsableItem('guitar1', function(source)
  TriggerClientEvent("dpemotes:emote", source, "guitar")
end)
ESX.RegisterUsableItem('guitar2', function(source)
  TriggerClientEvent("dpemotes:emote", source, "guitarelectric2")
end)
ESX.RegisterUsableItem('suitcase2', function(source)
  TriggerClientEvent("dpemotes:emote", source, "suitcase2")
end)
ESX.RegisterUsableItem('suitcase3', function(source)
  TriggerClientEvent("dpemotes:emote", source, "suitcase")
end)
